### PR TITLE
Adding support for importing a package

### PR DESCRIPTION
**Pull request by talitarossari**
Adding support for importing a package installed by pip

### CODE REVIEW

**Comment by rochacbruno** [comment]
Looks like this is the same problem of https://github.com/rochacbruno/flasgger/issues/102

I am going to write some tests for it and then merge your PR..

Thanks

**Comment by rochacbruno** [comment]
Steps needed to test this

- [ ] Create a installable package with api definitions 
- [ ] Create `examples/test_package.py` with an app using that package
- [ ] Check if addresses #102 problem

**Comment by rochacbruno** [comment]
@talitarossari still need help to reproduce the error.

Take a look at `etc/flasgger_package` and `tests/package_example`

Can you reproduce your case there?

**Comment by talitarossari** [comment]
@rochacbruno, sorry for waiting.
I was able to reproduce my situation (import the .yml from an external package).
For this, I needed to create another file "parameters.yml" and import it out of the package.
The error did not persist.
Pull requests #135

**Comment by ryanermita** [comment]
I found this issue thru the comment in `flasgger/utils.py` line 466 while im following the stack trace error.

I had an issue importing `.yml` files using `swag_from()` from different directory.
I found out that it changes the path or retrieving the `.yml` files from another directory.
In my case the `.yml` file directory became `relative_path/utils/path_to_swagger/my.yml` instead of `relative_path/path_to_swagger/my.yml`

to fix this issue on my end, I define the relative path of my `.yml` documentation.
```
# because my swagger docs is the same path as my api module.
BASE_SWAGGER_DOCS_PATH = os.path.dirname(__file__) + '/docs/swagger'`

@swag_from('%s/my.yml' % BASE_SWAGGER_DOCS_PATH)
...
```

**Pull request merged**
