### PR TITLE
Basic code for #51

### PR DESCRIPTION
**Pull request by AminHP**

### CODE REVIEW

**Comment by rochacbruno** [comment]
nice! I am going to test it later today!

**Comment by rochacbruno** [comment]
Hi! thanks @AminHP I did some changes and merged.

**Comment by AminHP** [comment]
Hi again. I had an egregious mistake. I used 404 status code for _bad_request_. Please change 404 to 400 or change all _bad_request_s. Sorry for that.

**Comment by AminHP** [comment]
I can send a new pull request if you want.

**Pull request merged**
